# =============================================================================
# CONFIGURACIÓN DEL SISTEMA DE INVENTARIO - SPRING BOOT 3.x
# =============================================================================
server.port=8080
server.servlet.context-path=/

# Configuración de Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/db_tienda_inventario?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Spring Data JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de Formato y Zona Horaria JSON
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=America/Lima
spring.jackson.serialization.fail-on-empty-beans=false

# Rutas de Reportes JasperReports
app.reports.path=classpath:reports/

# Configuración de Seguridad JWT (RBAC Granular)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
